### PR TITLE
Allow use from ClojureScript as well as Clojure

### PR DESCRIPTION
**Pull request by brunchboy**
This changes the source files to cross-platform with reader
conditionals. Almost all functionality works in ClojureScript as well
as Clojure, the sole exception being XML parsing, which relies on Java
libraries for which I knew of no drop-in replacements.

This also establishes a non-snapshot version so the project can be a
dependency of other projects which are being published as actual
releases.

### CODE REVIEW

**Comment by brunchboy** [comment]
Thanks for merging this! Are you willing to publish this project to clojars so people can use the official version rather than (as we must use now) non-canonical forks? Or if you don’t want to deal with setting up an account and managing releases, would you like me to do so?

**Comment by liebke** [comment]
Hi James,

Thanks for the pull request! 

I've added you as a collaborator on the analemma github repo, and just now realized that I never set up analemma on Clojars yet, so please feel free to do so.

David

**Comment by brunchboy** [comment]
Thank you, David! I would be happy to do so.

In case you’re curious about what brought me to analemma, I am using it to enable people to generate byte field diagrams like [this one](https://deepsymmetry.org/images/test.svg) using a nice, Clojure-powered domain-specific language inside of [Asciidoctor](https://asciidoctor.org) and (Antora)[https://antora.org].

**Comment by brunchboy** [comment]
All right, it has been published and tagged. If you do have a Clojars account (or set one up in the future), let me know, and I will add you to that group so you can publish releases as well.

**Comment by liebke** [comment]
> In case you’re curious about what brought me to analemma, I am using it to enable people to generate byte field diagrams like this one using a nice, Clojure-powered domain-specific language inside of Asciidoctor and (Antora)[https://antora.org].

Very nice!

And I do have a clojars account, liebke. 

Thanks again James,

David

**Comment by brunchboy** [comment]
Great, indeed you do, and you are now in the `analemma` group.

Cheers!

**Comment by brunchboy** [comment]
Sorry! In my original PR, I had not noticed that there were links in the Github Pages web site to the `.clj` versions of the source, so they have been broken for a bit. I just fixed that.

**Pull request merged**
